# Generated by Django 4.2 on 2024-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_cellphone_profile_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usersecret',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
