# Generated by Django 4.2 on 2024-03-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_planfeatures_plans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
