# Generated by Django 4.2 on 2024-03-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_plans_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('features', models.ManyToManyField(blank=True, to='dashboard.planfeatures')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly',
            field=models.ManyToManyField(blank=True, related_name='monthly_plans', to='dashboard.planitem'),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly',
            field=models.ManyToManyField(blank=True, related_name='yearly_plans', to='dashboard.planitem'),
        ),
    ]
