# Generated by Django 4.2 on 2024-04-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_plan_avatar_remove_plan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.specialization'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.jobtype'),
        ),
    ]
