# Generated by Django 4.2 on 2024-04-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_cvtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitem',
            name='features',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanFeatures',
        ),
        migrations.DeleteModel(
            name='PlanItem',
        ),
    ]
